# Generated by Django 3.1.7 on 2021-04-03 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210403_1716'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
