# Generated by Django 3.1.7 on 2021-04-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=70)),
                ('username', models.CharField(max_length=20)),
                ('rod', models.TextField(max_length=400)),
                ('meds', models.TextField(max_length=400)),
                ('nod', models.CharField(max_length=50)),
                ('dov', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=120)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
