# Generated by Django 3.1.7 on 2021-04-03 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_patient_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='dov',
            new_name='visit_date',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='meds',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='nod',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='rod',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='username',
        ),
        migrations.AddField(
            model_name='patient',
            name='docname',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='fname',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='lname',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='medicine',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='result',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='usrname',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
